### ISSUE TITLE
Lines instead of Shapes?

### ISSUE THREAD

**Issue by jmweeks101** [jmweeks101/Graphics3#6]
I was trying to visualize the different 3D shapes by drawing some by hand. I noticed that when doing so, I would draw the base shape, and then draw the parallel lines from it to create the 3D visual. That made me think: 

Would it be easier to create our 3D shapes by using the lines from the graphics package to create our object instead of trying to group 2D shapes together?

**Comment by sojdb** [comment]
That could work. I was thinking that with the combination of the 2D shapes and 2D rotation we would be able to simply create three 2D shapes that we could manipulate and group together to be the 3D shape, therefore only requiring us to manipulate 2 more shapes rather than 6 or so lines. Also, if we were to do the lines, would the 2D rotation then be pointless?

**Comment by jmweeks101** [comment]
I tried making a small trial program to test if making lines would be easier than making faces/2D shapes. Making lots of lines had multiple issues and doesn't seem like a good route. However, I found a way that seems to make a 3D shape (only can make rectangular prism) without having to use any rotating methods or in-depth math and calculations. I put the code below so you can test it out. Maybe there's an issues with it I don't see yet.  But it seems this might be an easier way of going about the project.

`import sys
sys.path.insert(0, '/Users/joshweeks/NSC/1fall/cs-135')
from graphics import *

#click anywhere to create initial base shape. Then, click on a second spot to create the 3D shape from it.
def main():
    win = GraphWin("test",500,500)
    win.setCoords(0,0,100,100)
    r = 10
    while True:
        click = win.getMouse()
        r1 = Rectangle(Point(click.getX()-r,click.getY()-r),Point(click.getX()+r,click.getY()+r))
        r1.setFill("blue")
        r1.draw(win)
        click = win.getMouse()
        faces = extrude(win,r,r1,click)
        win.getMouse()
        r1.undraw()
        for face in faces:
            face.undraw()

def extrude(win,r,r1,p):
    #setup
    faces = []
    dirs = {"N":[[-1,1],[1,1]],"S":[[-1,-1],[1,-1]],"E":[[1,1],[1,-1]],"W":[[-1,1],[-1,-1]]}
    #locates second click relative to first click
    loc = findPoint(r1,p)
    #make north/south face
    ps = []
    ps.append(Point(r1.getCenter().getX()+r*dirs[loc[0]][0][0],r1.getCenter().getY()+r*dirs[loc[0]][0][1]))
    ps.append(Point(p.getX()+r*dirs[loc[0]][0][0],p.getY()+r*dirs[loc[0]][0][1]))
    ps.append(Point(p.getX()+r*dirs[loc[0]][1][0],p.getY()+r*dirs[loc[0]][1][1]))
    ps.append(Point(r1.getCenter().getX()+r*dirs[loc[0]][1][0],r1.getCenter().getY()+r*dirs[loc[0]][1][1]))
    faces.append(Polygon(ps))
    #make west/east face
    ps = []
    ps.append(Point(r1.getCenter().getX()+r*dirs[loc[1]][0][0],r1.getCenter().getY()+r*dirs[loc[1]][0][1]))
    ps.append(Point(p.getX()+r*dirs[loc[1]][0][0],p.getY()+r*dirs[loc[1]][0][1]))
    ps.append(Point(p.getX()+r*dirs[loc[1]][1][0],p.getY()+r*dirs[loc[1]][1][1]))
    ps.append(Point(r1.getCenter().getX()+r*dirs[loc[1]][1][0],r1.getCenter().getY()+r*dirs[loc[1]][1][1]))
    faces.append(Polygon(ps))
    #draw and fill side faces
    for face in faces:
        face.setFill("blue")
        face.draw(win)
    return faces

def findPoint(r1,p):
    if p.getX()>r1.getCenter().getX():
        if p.getY()>r1.getCenter().getY():
            return "NE"
        else:
            return "SE"
    else:
        if p.getY()>r1.getCenter().getY():
            return "NW"
        else:
            return "SW"

if __name__ == "__main__":
    main()
`
