### ISSUE TITLE
What 3D shapes do we want to attempt exactly?

### ISSUE THREAD

**Issue by sojdb** [jmweeks101/Graphics3#7]
As we are getting most of the base code done, we are approaching the process of making the shapes. I was thinking of doing three shapes, such as a Sphere, Pyramid, and Rectangular Prism/Cube (go hand in hand with each other). Are those three shapes a good goal, or are there any changes in which we should make?

**Comment by jmweeks101** [comment]
We've decided to cover all Prisms and Pyramids, and potentially spheres in the future.
